# Generated by Django 2.0 on 2018-11-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_salida',
            name='cabeza_kardex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrada_salida',
            name='cola_kardex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrada_salida',
            name='siguiente_kardex',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='entrada_salida',
            name='tipo_movimiento',
            field=models.BooleanField(default=False),
        ),
    ]
