# Generated by Django 2.0.5 on 2018-11-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
