# Generated by Django 2.0 on 2018-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='costo_unitario',
            field=models.FloatField(default=0.0),
        ),
    ]
