# Generated by Django 2.0.5 on 2018-11-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0002_proceso_terminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion_Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='asignar_cif',
            name='proceso_cif',
        ),
        migrations.RemoveField(
            model_name='asignar_mano_obra',
            name='proceso_mo',
        ),
        migrations.RemoveField(
            model_name='asignar_materia_prima',
            name='proceso_mp',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='programacion',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='terminado',
        ),
        migrations.AddField(
            model_name='programacion_proceso',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad_costos.Proceso'),
        ),
        migrations.AddField(
            model_name='programacion_proceso',
            name='programacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad_costos.Programacion'),
        ),
        migrations.AddField(
            model_name='asignar_cif',
            name='proceso_prog_cif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad_costos.Programacion_Proceso'),
        ),
        migrations.AddField(
            model_name='asignar_mano_obra',
            name='proceso_prog_mo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad_costos.Programacion_Proceso'),
        ),
        migrations.AddField(
            model_name='asignar_materia_prima',
            name='proceso_prog_mp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad_costos.Programacion_Proceso'),
        ),
    ]
