# Generated by Django 2.0.5 on 2018-11-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('contabilidad_costos', '0003_auto_20181122_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='cuenta_proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.CuentaHija'),
        ),
    ]
