# Generated by Django 2.0.5 on 2018-11-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0004_proceso_cuenta_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_mano_obra',
            name='monto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
