# Generated by Django 2.0.5 on 2018-11-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0005_asignar_mano_obra_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignar_materia_prima',
            old_name='precio_unitario_mp',
            new_name='monto',
        ),
    ]
