# Generated by Django 2.0.5 on 2018-11-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0006_auto_20181123_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_cif',
            name='monto',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
