# Generated by Django 2.0.5 on 2018-11-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_costos', '0007_asignar_cif_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='costo_unitario',
            field=models.FloatField(default=0.0),
        ),
    ]
