# Generated by Django 2.0 on 2018-11-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_cuenta_codigo_grup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='codigo_agrup',
            new_name='agrupacion',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='codigo_grup',
            new_name='grupo',
        ),
    ]
