# Generated by Django 2.0 on 2018-11-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181109_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='agrupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Agrupacion'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Grupo'),
        ),
    ]
