# Generated by Django 2.0 on 2018-11-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20181109_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='grupo',
        ),
    ]
