# Generated by Django 2.0 on 2018-11-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_cuenta_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='agrupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Agrupacion'),
        ),
    ]
