# Generated by Django 2.0 on 2018-11-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20181109_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codigo_padre',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_acreedor_cuenta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_deudor_cuenta',
            field=models.FloatField(default=0.0),
        ),
    ]
