# Generated by Django 2.0 on 2018-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20181109_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codigo_cuenta',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
