# Generated by Django 2.0 on 2018-11-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20181109_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaHija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_padre', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre_cuenta', models.CharField(max_length=100)),
                ('codigo_cuenta', models.CharField(blank=True, max_length=7)),
                ('descripcion_cuenta', models.CharField(max_length=100)),
                ('saldo_deudor_cuenta', models.FloatField(default=0.0)),
                ('saldo_acreedor_cuenta', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='codigo_padre',
        ),
        migrations.AddField(
            model_name='cuentahija',
            name='agrupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cuenta'),
        ),
    ]
