# Generated by Django 2.0 on 2018-11-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20181109_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentahija',
            old_name='agrupacion',
            new_name='padre',
        ),
    ]
