# Generated by Django 2.0 on 2018-11-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20181109_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentahija',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cuenta'),
        ),
    ]
