# Generated by Django 2.0 on 2018-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20181109_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentahija',
            name='padre',
            field=models.IntegerField(),
        ),
    ]
