# Generated by Django 2.0 on 2018-11-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20181109_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codigo_cuenta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
