# Generated by Django 2.0 on 2018-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20181109_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='debe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='haber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cuentahija',
            name='debe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cuentahija',
            name='haber',
            field=models.FloatField(default=0.0),
        ),
    ]
