# Generated by Django 2.0 on 2018-11-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_auto_20181110_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentahija',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cuenta'),
        ),
    ]
