# Generated by Django 2.0 on 2018-11-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancePeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_deudor', models.FloatField()),
                ('saldo_acreedor', models.FloatField()),
                ('cuenta_balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_periodo', models.DateField()),
                ('final_periodo', models.DateField()),
                ('estado_periodo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='balanceperiodo',
            name='periodo_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='periodo.Periodo'),
        ),
    ]
