# Generated by Django 2.0 on 2018-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='periodo_ajuste',
            field=models.BooleanField(default=False),
        ),
    ]
