# Generated by Django 2.0 on 2019-11-19 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nota', models.CharField(max_length=50)),
                ('descripcion_nota', models.CharField(max_length=300)),
                ('periodo_nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='periodo.Periodo')),
            ],
        ),
    ]
