# Generated by Django 2.0 on 2018-11-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_auto_20181110_1635'),
        ('periodo', '0002_periodo_periodo_ajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceperiodo',
            name='hija_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.CuentaHija'),
        ),
    ]
