# Generated by Django 2.0 on 2018-11-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0003_balanceperiodo_hija_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceperiodo',
            name='saldo_acreedor_h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balanceperiodo',
            name='saldo_deudor_h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='balanceperiodo',
            name='saldo_acreedor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='balanceperiodo',
            name='saldo_deudor',
            field=models.FloatField(default=0.0),
        ),
    ]
